name: fuzzy
channels:
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20211102.0
  - altair=5.0.1
  - arrow-cpp=11.0.0
  - asttokens=2.2.1
  - attrs=23.1.0
  - aws-c-common=0.6.8
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.185
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - black=23.7.0
  - blinker=1.6.2
  - boost-cpp=1.82.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.7.22
  - cachetools=5.3.1
  - certifi=2023.7.22
  - charset-normalizer=3.2.0
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.1.4
  - debugpy=1.6.8
  - decorator=5.1.1
  - exceptiongroup=1.1.3
  - executing=1.2.0
  - freetype=2.12.1
  - gflags=2.2.2
  - gitdb=4.0.10
  - gitpython=3.1.32
  - glog=0.5.0
  - grpc-cpp=1.48.2
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.0.1
  - iniconfig=2.0.0
  - intel-openmp=2023.2.0
  - ipykernel=6.25.1
  - ipython=8.14.0
  - ipywidgets=8.1.0
  - isort=5.12.0
  - jedi=0.19.0
  - jinja2=3.1.2
  - jsonschema=4.19.0
  - jsonschema-specifications=2023.7.1
  - jupyter_client=8.3.0
  - jupyter_core=5.3.1
  - jupyterlab_widgets=3.0.8
  - krb5=1.21.2
  - lcms2=2.15
  - lerc=4.0.0
  - levenshtein=0.21.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=8.2.1
  - libdeflate=1.18
  - libffi=3.4.2
  - libhwloc=2.9.2
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libsqlite=3.43.0
  - libssh2=1.11.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libwebp-base=1.3.1
  - libxcb=1.15
  - libxml2=2.11.5
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown-it-py=3.0.0
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mdurl=0.1.0
  - mkl=2022.1.0
  - msys2-conda-epoch=20160418
  - mypy_extensions=1.0.0
  - nest-asyncio=1.5.6
  - numpy=1.25.2
  - openjpeg=2.5.0
  - openssl=3.1.2
  - orc=1.7.4
  - packaging=23.1
  - pandas=2.0.3
  - parso=0.8.3
  - pathspec=0.11.2
  - pickleshare=0.7.5
  - pillow=9.5.0
  - pip=23.2.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - pluggy=1.3.0
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - protobuf=3.20.3
  - psutil=5.9.5
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pure_eval=0.2.2
  - pyarrow=11.0.0
  - pydeck=0.8.0
  - pygments=2.16.1
  - pympler=1.0.1
  - pysocks=1.7.1
  - pytest=7.4.0
  - python=3.9.17
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytz=2023.3
  - pywin32=304
  - pyyaml=6.0.1
  - pyzmq=25.1.1
  - rapidfuzz=2.15.1
  - re2=2022.04.01
  - referencing=0.30.2
  - requests=2.31.0
  - rich=13.5.1
  - rpds-py=0.9.2
  - ruff=0.0.286
  - setuptools=68.1.2
  - six=1.16.0
  - smmap=3.0.5
  - snappy=1.1.10
  - stack_data=0.6.2
  - streamlit=1.26.0
  - tbb=2021.10.0
  - tenacity=8.2.3
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.3.3
  - traitlets=5.9.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - tzlocal=3.0
  - ucrt=10.0.22621.0
  - urllib3=2.0.4
  - utf8proc=2.6.1
  - validators=0.21.2
  - vc=14.3
  - vc14_runtime=14.36.32532
  - vs2015_runtime=14.36.32532
  - watchdog=3.0.0
  - wcwidth=0.2.6
  - wheel=0.41.2
  - widgetsnbextension=4.0.8
  - win_inet_pton=1.1.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.16.2
  - zlib=1.2.13
  - zstd=1.5.5
